language: node_js
node_js:
  - "8"
  - "9"

cache: yarn

install: yarn
script:
  - yarn lint
  - yarn test

jobs:
  include:
    - stage: npm release snapshot
      node_js: "8"
      script:
        - yarn compile
        - export SNAPSHOT_TAG=$(npm-snapshot $(date +%s))
        - echo "$SNAPSHOT_TAG"
      before_deploy:
        - cd dist
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        tag: "$SNAPSHOT_TAG"
        on:
          all_branches: true
    - stage: npm release
      if: tag IS present
      node_js: "8"
      script: yarn compile
      before_deploy:
        - cd dist
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          if: branch = master AND tag = true
